// Frontend/implementations/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { InitialSettings } from './pixel-streaming-wrapper/initial-settings.interface';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})


export class AppComponent {
  initialSettings: InitialSettings = {};

  ngOnInit(): void {
    this.initialSettings = {
      AutoPlayVideo: true,
      AutoConnect: true,
      ss: 'ws://localhost:80',
      StartVideoMuted: true,
      HoveringMouse: true
    }
  }
}

<div style="height: 100% ; width: 100%">
  <app-pixel-streaming-wrapper [initialSettings]='initialSettings' />
</div>

// Frontend/implementations/react/src/components/App.tsx
import React from 'react';
import { PixelStreamingWrapper } from './PixelStreamingWrapper';

export const App = () => {
    return (
        <div
            style={{
                height: '100%',
                width: '100%'
            }}
        >
            <PixelStreamingWrapper
                initialSettings={{
                    AutoPlayVideo: true,
                    AutoConnect: true,
                    ss: 'ws://localhost:80',
                    StartVideoMuted: true,
                    HoveringMouse: true
                }}
            />
        </div>
    );
};
