// Frontend/implementations/react/src/components/PixelStreamingWrapper.tsx
// Copyright Epic Games, Inc. All Rights Reserved.

import React, { useEffect, useRef, useState } from 'react';
import {
    Config,
    AllSettings,
    PixelStreaming
} from '@epicgames-ps/lib-pixelstreamingfrontend-ue5.4';

export interface PixelStreamingWrapperProps {
    initialSettings?: Partial<AllSettings>;
}

export const PixelStreamingWrapper = ({
    initialSettings
}: PixelStreamingWrapperProps) => {
    // A reference to parent div element that the Pixel Streaming library attaches into:
    const videoParent = useRef<HTMLDivElement>(null);

    // Pixel streaming library instance is stored into this state variable after initialization:
    const [pixelStreaming, setPixelStreaming] = useState<PixelStreaming>();
    
    // A boolean state variable that determines if the Click to play overlay is shown:
    const [clickToPlayVisible, setClickToPlayVisible] = useState(false);

    // Run on component mount:
    useEffect(() => {
        if (videoParent.current) {
            // Attach Pixel Streaming library to videoParent element:
            const config = new Config({ initialSettings });
            const streaming = new PixelStreaming(config, {
                videoElementParent: videoParent.current
            });
            
            // register a playStreamRejected handler to show Click to play overlay if needed:
            streaming.addEventListener('playStreamRejected', () => {
                setClickToPlayVisible(true);
            });

            // Save the library instance into component state so that it can be accessed later:
            setPixelStreaming(streaming);

            // Clean up on component unmount:
            return () => {
                try {
                    streaming.disconnect();
                } catch {}
            };
        }
    }, []);

    return (
        <div
            style={{
                width: '100%',
                height: '100%',
                position: 'relative'
            }}
        >
            <div
                style={{
                    width: '100%',
                    height: '100%'
                }}
                ref={videoParent}
            />
            {clickToPlayVisible && (
                <div
                    style={{
                        position: 'absolute',
                        top: 0,
                        left: 0,
                        width: '100%',
                        height: '100%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        cursor: 'pointer'
                    }}
                    onClick={() => {
                        pixelStreaming?.play();
                        setClickToPlayVisible(false);
                    }}
                >
                    <div>Click to play</div>
                </div>
            )}
        </div>
    );
};

// Frontend/implementations/angular/src/app/pixel-streaming-wrapper/pixel-streaming-wrapper.component.ts
import { Component, ElementRef, Input, OnInit, Renderer2, ViewChild, booleanAttribute } from '@angular/core';
import { InitialSettings } from './initial-settings.interface';
import {
  Config,
  AllSettings,
  PixelStreaming
} from '@epicgames-ps/lib-pixelstreamingfrontend-ue5.2';


@Component({
  selector: 'app-pixel-streaming-wrapper',
  templateUrl: './pixel-streaming-wrapper.component.html',
  styleUrls: ['./pixel-streaming-wrapper.component.css']
})
export class PixelStreamingWrapperComponent implements OnInit {
  @Input() initialSettings: Partial<AllSettings> | undefined = undefined;
  // A reference to parent div element that the Pixel Streaming library attaches into:
  @ViewChild('videoParent', { read: ElementRef }) videoParent:
    | ElementRef<any>
    | undefined;
  // Pixel streaming library instance is stored into this state variable after initialization:
  pixelStreaming: PixelStreaming | undefined = undefined;
  config: Config | undefined = undefined;
  // A boolean state variable that determines if the Click to play overlay is shown:
  clickToPlayVisible: boolean = false;

  constructor(
    private elementRef: ElementRef,
    private renderer: Renderer2,
  ) { }

  ngOnInit(): void {

  }

  ngAfterViewInit(): void {
    // Run on component mount: When the component's view has been initialized.

    // Attach Pixel Streaming library to videoParent element:
    if (this.videoParent?.nativeElement) {
      this.config = new Config({ initialSettings: this.initialSettings });
      // Save the library instance into component state so that it can be accessed later:
      this.pixelStreaming = new PixelStreaming(this.config, {
        videoElementParent: this.videoParent?.nativeElement
      });

      // register a playStreamRejected handler to show Click to play overlay if needed:
      this.pixelStreaming?.addEventListener('playStreamRejected', () => {
        this.clickToPlayVisible = true;
      });
    }

  }

  ngOnDestroy(): void {
    // Clean up on component unmount: Called once, before the instance is destroyed.
    this.pixelStreaming?.disconnect();
  }

}

<div style="height: 100% ; width: 100%; position: relative">
    <div #videoParent style="height: 100% ; width: 100%;">
        <div *ngIf="clickToPlayVisible" (click)="pixelStreaming?.play();clickToPlayVisible=false;"
            style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; cursor: pointer">
            <div>Click to play</div>
        </div>
    </div>
</div>
